[project]
name = "agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.9.1",
    "duckduckgo-search>=8.1.1",
    "langchain-community>=0.4.1",
    "openai-agents>=0.5.1",
]
